//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSQLScript.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSSQLScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///SET ARITHABORT ON
        ///SET CONCAT_NULL_YIELDS_NULL ON
        ///SET QUOTED_IDENTIFIER ON
        ///SET ANSI_NULLS ON
        ///SET ANSI_PADDING ON
        ///SET ANSI_WARNINGS ON
        ///SET NUMERIC_ROUNDABORT OFF
        ///
        ///declare @crlf char(2)
        ///SET @crlf=char(13)+char(10)
        ///
        ///;WITH ColumnDefs as
        ///(
        ///  select TableObj=c.[object_id]
        ///        ,ColSeq=c.column_id
        ///        ,ColumnDef=quotename(c.Name)+&apos; &apos;
        ///                  +case 
        ///                     when c.is_computed=1 then &apos;as &apos;+coalesce(k.[definition],&apos;&apos;)
        ///                         +case when k.is_persisted= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ;WITH TypeDef AS(
        ///  SELECT TypeName=QUOTENAME( SCHEMA_NAME(t.schema_id))+&apos;.&apos;+QUOTENAME(t.name)
        ///        ,ParentName=TYPE_NAME(t.system_type_id)+&apos;&apos;
        ///                 +case
        ///                    when DataType in (&apos;decimal&apos;,&apos;numeric&apos;) then &apos;(&apos;+cast(t.precision as varchar(10))+case when t.scale&lt;&gt;0 then &apos;,&apos;+cast(t.scale as varchar(10)) else &apos;&apos; end +&apos;)&apos;
        ///                    when DataType in (&apos;char&apos;,&apos;varchar&apos;,&apos;nchar&apos;,&apos;nvarchar&apos;,&apos;binary&apos;,&apos;varbinary&apos;) then &apos;(&apos;+case when t.max_length=-1 then &apos;max&apos; else case when Data [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string types {
            get {
                return ResourceManager.GetString("types", resourceCulture);
            }
        }
    }
}
